name: Build and Execute Tests

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v1
      - name: Build Opal
        run: sbt -J-Xmx20G cleanBuild
  
  formatting:
    runs-on: self-hosted
    needs: build
    
    steps:
      - name: Test Formatting
        run: git diff --exit-code

  test:
    runs-on: self-hosted
    needs: build

    steps:
      - name: Run Tests
        run: sbt -J-Xmx20G test

  it-test:
    runs-on: self-hosted
    needs: build

    steps:
    - uses: actions/checkout@v1
    - name: Run Integration Tests
      run: sbt -J-Xmx40G cleanBuild it:test