name: Build and Execute Tests

on:
  push:
    branches:
      - master      
  pull_request:
    branches:
      - master
      - develop
  merge_group:

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v1
      - name: Build Opal
        run: sbt -J-Xmx20G cleanBuild
      
      - name: Check formatting
        run: git diff --exit-code
        
      - name: Run tests
        run: sbt -J-Xmx20G test

      - name: Run LLVM tests
        run: sbt -J-Xmx20G "project LLVM;test;project ValidateCross;test"

  it-test:
    runs-on: self-hosted
    needs: build

    if: github.event_name == 'push' || github.event_name == 'merge_group' 

    steps:
    - uses: actions/checkout@v1
    - name: Run Integration Tests
      run: sbt -J-Xmx40G cleanBuild it:test
    - name: Run LLVM Integration Tests
      run: sbt -J-Xmx40G "project LLVM;it:test;project ValidateCross;it:test"
